version: '3'

services:
  t1:
    container_name: pgpass
    image: maven:3.5.3-jdk-8-alpine
    volumes:
      - ${HOME}/.m2:/root/.m2
      - ./:/wd
    working_dir: /wd
    command: ["mvn", "clean", "install"]
